services:
  omni-stack-db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  omni-stack-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: